@echo off
echo check out the entire inc directory from source control before executing this
echo check that the src and target directories below are correct
echo if you have added any other include files from open cascade make sure they are named below
set src=C:\OpenCASCADE6.5.3\ros\inc
set target=G:\Documents\XbimCP\XbimFramework\Dev\OpenCascadeUpgrade\Xbim.ModelGeometry\OpenCascade\inc
echo Copying from %src% to %target%
pause
copy %src%\GeomAbs_JoinType.hxx %target%
copy %src%\BRepBuilderAPI_PipeError.hxx %target%
copy %src%\BRepBuilderAPI_TransitionMode.hxx %target%
copy %src%\BRepFill_DataMapNodeOfDataMapOfShapeDataMapOfShapeListOfShape.hxx %target%
copy %src%\BRepFill_DataMapOfShapeDataMapOfShapeListOfShape.hxx %target%
copy %src%\BRepFill_Evolved.hxx %target%
copy %src%\Handle_BRepFill_DataMapNodeOfDataMapOfShapeDataMapOfShapeListOfShape.hxx %target%
copy %src%\Handle_BRepFill_PipeShell.hxx %target%
copy %src%\BRepOffsetAPI_MakeEvolved.hxx %target%
copy %src%\BRepOffsetAPI_MakePipeShell.hxx %target%
copy %src%\Handle_Law_Function.hxx %target%

copy %src%\Adaptor3d_Curve.hxx %target%
copy %src%\Adaptor3d_Surface.hxx %target%
copy %src%\Adaptor3d_SurfacePtr.hxx %target% 
copy %src%\Bnd_Box.hxx %target%
copy %src%\Bnd_Box.lxx %target%
copy %src%\Bnd_Sphere.hxx %target%
copy %src%\Bnd_Sphere.lxx %target%
copy %src%\BOPTools_PDSFiller.hxx %target%
copy %src%\BOP_Operation.hxx %target%
copy %src%\BOP_PBuilder.hxx %target%
copy %src%\BRepAdaptor_Curve.hxx %target%
copy %src%\BRepAlgoAPI_BooleanOperation.hxx %target%
copy %src%\BRepAlgoAPI_Common.hxx %target%
copy %src%\BRepAlgoAPI_Cut.hxx %target%
copy %src%\BRepAlgoAPI_Fuse.hxx %target%
copy %src%\BRepAlgo_BooleanOperation.hxx %target%
copy %src%\BRepAlgo_Cut.hxx %target%
copy %src%\BRepAlgo_Section.hxx %target%
copy %src%\BRepBndLib.hxx %target%
copy %src%\BRepBuilderAPI_Collect.hxx %target%
copy %src%\BRepBuilderAPI_Command.hxx %target%
copy %src%\BRepBuilderAPI_EdgeError.hxx %target%
copy %src%\BRepBuilderAPI_FaceError.hxx %target%
copy %src%\BRepBuilderAPI_FindPlane.hxx %target%
copy %src%\BRepBuilderAPI_GTransform.hxx %target%
copy %src%\BRepBuilderAPI_MakeEdge.hxx %target%
copy %src%\BRepBuilderAPI_MakeFace.hxx %target%
copy %src%\BRepBuilderAPI_MakePolygon.hxx %target%
copy %src%\BRepBuilderAPI_MakeShape.hxx %target%
copy %src%\BRepBuilderAPI_MakeSolid.hxx %target%
copy %src%\BRepBuilderAPI_MakeWire.hxx %target%
copy %src%\BRepBuilderAPI_ModifyShape.hxx %target%
copy %src%\BRepBuilderAPI_Sewing.hxx %target%
copy %src%\BRepBuilderAPI_Sewing.lxx %target%
copy %src%\BRepBuilderAPI_Transform.hxx %target%
copy %src%\BRepBuilderAPI_WireError.hxx %target%
copy %src%\BRepCheck_Analyzer.hxx %target%
copy %src%\BRepCheck_Analyzer.lxx %target%
copy %src%\BRepCheck_DataMapOfShapeResult.hxx %target%
copy %src%\BRepGProp.hxx %target%
copy %src%\BRepLib.hxx %target%
copy %src%\BRepLib_Command.hxx %target%
copy %src%\BRepLib_EdgeError.hxx %target%
copy %src%\BRepLib_FaceError.hxx %target%
copy %src%\BRepLib_FindSurface.hxx %target%
copy %src%\BRepLib_FuseEdges.hxx %target%
copy %src%\BRepLib_MakeEdge.hxx %target%
copy %src%\BRepLib_MakeFace.hxx %target%
copy %src%\BRepLib_MakePolygon.hxx %target%
copy %src%\BRepLib_MakeShape.hxx %target%
copy %src%\BRepLib_MakeSolid.hxx %target%
copy %src%\BRepLib_MakeWire.hxx %target%
copy %src%\BRepLib_ShapeModification.hxx %target%
copy %src%\BRepLib_WireError.hxx %target%
copy %src%\BRepMesh.hxx %target%
copy %src%\BRepMesh_DiscretRoot.hxx %target%
copy %src%\BRepMesh_PDiscretRoot.hxx %target%
copy %src%\BRepMesh_IncrementalMesh.hxx %target%
copy %src%\BRepPrimAPI_MakeHalfSpace.hxx %target%
copy %src%\BRepPrimAPI_MakePrism.hxx %target%
copy %src%\BRepPrimAPI_MakeRevol.hxx %target%
copy %src%\BRepPrimAPI_MakeSweep.hxx %target%
copy %src%\BRepSweep_Array2OfShapesOfNumLinearRegularSweep.hxx %target%
copy %src%\BRepSweep_Builder.hxx %target%
copy %src%\BRepSweep_Builder.lxx %target%
copy %src%\BRepSweep_NumLinearRegularSweep.hxx %target%
copy %src%\BRepSweep_Prism.hxx %target%
copy %src%\BRepSweep_Revol.hxx %target%
copy %src%\BRepSweep_Rotation.hxx %target%
copy %src%\BRepSweep_Tool.hxx %target%
copy %src%\BRepSweep_Translation.hxx %target%
copy %src%\BRepSweep_Trsf.hxx %target%
copy %src%\BRepTools.hxx %target%
copy %src%\BRepTools_Modifier.hxx %target%
copy %src%\BRepTools_Modifier.lxx %target%
copy %src%\BRepTools_ReShape.hxx %target%
copy %src%\BRepTools_WireExplorer.hxx %target%
copy %src%\BRep_Builder.hxx %target%
copy %src%\BRep_Builder.lxx %target%
copy %src%\BRep_ListOfPointRepresentation.hxx %target%
copy %src%\BRep_TFace.hxx %target%
copy %src%\BRep_TFace.lxx %target%
copy %src%\BRep_Tool.hxx %target%
copy %src%\BRep_TVertex.hxx %target%
copy %src%\BRep_TVertex.lxx %target%
copy %src%\Extrema_ExtAlgo.hxx %target%
copy %src%\Extrema_ExtFlag.hxx %target%
copy %src%\Extrema_ExtPElS.hxx %target%
copy %src%\Extrema_ExtPS.hxx %target%
copy %src%\Extrema_FuncExtPS.hxx %target%
copy %src%\Extrema_GenExtPS.hxx %target%
copy %src%\Extrema_HUBTreeOfSphere.hxx %target%
copy %src%\Extrema_POnSurf.hxx %target%
copy %src%\Extrema_POnSurf.lxx %target%
copy %src%\Extrema_SequenceOfPOnSurf.hxx %target%
copy %src%\gce_ErrorType.hxx %target%
copy %src%\GCPnts_TangentialDeflection.hxx %target%
copy %src%\GCPnts_TangentialDeflection.lxx %target%
copy %src%\GC_MakeArcOfCircle.hxx %target%
copy %src%\GC_MakeArcOfEllipse.hxx %target%
copy %src%\GC_MakeCircle.hxx %target%
copy %src%\GC_MakeSegment.hxx %target%
copy %src%\GC_Root.hxx %target%
copy %src%\GC_Root.lxx %target%
copy %src%\GeomAbs_CurveType.hxx %target%
copy %src%\GeomAbs_Shape.hxx %target%
copy %src%\GeomAbs_SurfaceType.hxx %target%
copy %src%\GeomAdaptor_Curve.hxx %target%
copy %src%\GeomAdaptor_Curve.lxx %target%
copy %src%\GeomAdaptor_Surface.hxx %target%
copy %src%\GeomAdaptor_Surface.lxx %target%
copy %src%\GeomAPI_ProjectPointOnSurf.hxx %target%
copy %src%\GeomAPI_ProjectPointOnSurf.lxx %target%
copy %src%\GeomLib_IsPlanarSurface.hxx %target%
copy %src%\GeomLProp_SLProps.hxx %target%
copy %src%\Geom_Circle.hxx %target%
copy %src%\Geom_Conic.hxx %target%
copy %src%\Geom_Curve.hxx %target%
copy %src%\Geom_ElementarySurface.hxx %target%
copy %src%\Geom_Geometry.hxx %target%
copy %src%\Geom_Line.hxx %target%
copy %src%\Geom_Plane.hxx %target%
copy %src%\Geom_Surface.hxx %target%
copy %src%\gp.hxx %target%
copy %src%\gp.lxx %target%
copy %src%\GProp_GProps.hxx %target%
copy %src%\gp_Ax1.hxx %target%
copy %src%\gp_Ax1.lxx %target%
copy %src%\gp_Ax2.hxx %target%
copy %src%\gp_Ax2.lxx %target%
copy %src%\gp_Ax2d.hxx %target%
copy %src%\gp_Ax2d.lxx %target%
copy %src%\gp_Ax3.hxx %target%
copy %src%\gp_Ax3.lxx %target%
copy %src%\gp_Circ.hxx %target%
copy %src%\gp_Circ.lxx %target%
copy %src%\gp_Dir.hxx %target%
copy %src%\gp_Dir.lxx %target%
copy %src%\gp_Dir2d.hxx %target%
copy %src%\gp_Dir2d.lxx %target%
copy %src%\gp_Elips.hxx %target%
copy %src%\gp_Elips.lxx %target%
copy %src%\gp_GTrsf.hxx %target%
copy %src%\gp_GTrsf.lxx %target%
copy %src%\gp_Hypr.hxx %target%
copy %src%\gp_Hypr.lxx %target%
copy %src%\gp_Lin.hxx %target%
copy %src%\gp_Lin.lxx %target%
copy %src%\gp_Mat.hxx %target%
copy %src%\gp_Mat.lxx %target%
copy %src%\gp_Mat2d.hxx %target%
copy %src%\gp_Mat2d.lxx %target%
copy %src%\gp_Parab.hxx %target%
copy %src%\gp_Parab.lxx %target%
copy %src%\gp_Pln.hxx %target%
copy %src%\gp_Pln.lxx %target%
copy %src%\gp_Pnt.hxx %target%
copy %src%\gp_Pnt.lxx %target%
copy %src%\gp_Pnt2d.hxx %target%
copy %src%\gp_Pnt2d.lxx %target%
copy %src%\gp_Trsf.hxx %target%
copy %src%\gp_Trsf.lxx %target%
copy %src%\gp_Trsf2d.hxx %target%
copy %src%\gp_Trsf2d.lxx %target%
copy %src%\gp_TrsfForm.hxx %target%
copy %src%\gp_Vec.hxx %target%
copy %src%\gp_Vec.lxx %target%
copy %src%\gp_Vec2d.hxx %target%
copy %src%\gp_Vec2d.lxx %target%
copy %src%\gp_VectorWithNullMagnitude.hxx %target%
copy %src%\gp_XY.hxx %target%
copy %src%\gp_XY.lxx %target%
copy %src%\gp_XYZ.hxx %target%
copy %src%\gp_XYZ.lxx %target%
copy %src%\Handle_Adaptor3d_HCurve.hxx %target%
copy %src%\Handle_Adaptor3d_HCurveOnSurface.hxx %target%
copy %src%\Handle_Adaptor3d_HSurface.hxx %target%
copy %src%\Handle_Bnd_HArray1OfSphere.hxx %target%
copy %src%\Handle_BOP_HistoryCollector.hxx %target%
copy %src%\Handle_BRepBuilderAPI_Sewing.hxx %target%
copy %src%\Handle_BRepCheck_DataMapNodeOfDataMapOfShapeResult.hxx %target%
copy %src%\Handle_BRepCheck_Result.hxx %target%
copy %src%\Handle_BRepMesh_DiscretRoot.hxx %target%
copy %src%\Handle_BRepMesh_FastDiscret.hxx %target%
copy %src%\Handle_BRepMesh_IncrementalMesh.hxx %target%
copy %src%\Handle_BRepSweep_SequenceNodeOfSequenceOfShapesOfNumLinearRegularSweep.hxx %target%
copy %src%\Handle_BRepTools_Modification.hxx %target%
copy %src%\Handle_BRepTools_ReShape.hxx %target%
copy %src%\Handle_BRep_ListNodeOfListOfPointRepresentation.hxx %target%
copy %src%\Handle_BRep_PointRepresentation.hxx %target%
copy %src%\Handle_BRep_TFace.hxx %target%
copy %src%\Handle_BRep_TVertex.hxx %target%
copy %src%\Handle_Extrema_SequenceNodeOfSequenceOfPOnSurf.hxx %target%
copy %src%\Handle_Geom2d_Curve.hxx %target%
copy %src%\Handle_Geom2d_Geometry.hxx %target%
copy %src%\Handle_Geom_BezierCurve.hxx %target%
copy %src%\Handle_Geom_BezierSurface.hxx %target%
copy %src%\Handle_Geom_BoundedCurve.hxx %target%
copy %src%\Handle_Geom_BoundedSurface.hxx %target%
copy %src%\Handle_Geom_BSplineCurve.hxx %target%
copy %src%\Handle_Geom_BSplineSurface.hxx %target%
copy %src%\Handle_Geom_Circle.hxx %target%
copy %src%\Handle_Geom_Conic.hxx %target%
copy %src%\Handle_Geom_Curve.hxx %target%
copy %src%\Handle_Geom_ElementarySurface.hxx %target%
copy %src%\Handle_Geom_Geometry.hxx %target%
copy %src%\Handle_Geom_Line.hxx %target%
copy %src%\Handle_Geom_Plane.hxx %target%
copy %src%\Handle_Geom_Surface.hxx %target%
copy %src%\Handle_Geom_TrimmedCurve.hxx %target%
copy %src%\Handle_gp_VectorWithNullMagnitude.hxx %target%
copy %src%\Handle_Message_ProgressIndicator.hxx %target%
copy %src%\Handle_MMgt_TShared.hxx %target%
copy %src%\Handle_Poly_Polygon2D.hxx %target%
copy %src%\Handle_Poly_Polygon3D.hxx %target%
copy %src%\Handle_Poly_PolygonOnTriangulation.hxx %target%
copy %src%\Handle_Poly_Triangulation.hxx %target%
copy %src%\Handle_ShapeAnalysis_Surface.hxx %target%
copy %src%\Handle_ShapeAnalysis_Wire.hxx %target%
copy %src%\Handle_ShapeBuild_ReShape.hxx %target%
copy %src%\Handle_ShapeExtend_BasicMsgRegistrator.hxx %target%
copy %src%\Handle_ShapeExtend_WireData.hxx %target%
copy %src%\Handle_ShapeFix_Edge.hxx %target%
copy %src%\Handle_ShapeFix_Face.hxx %target%
copy %src%\Handle_ShapeFix_Root.hxx %target%
copy %src%\Handle_ShapeFix_Shape.hxx %target%
copy %src%\Handle_ShapeFix_Shell.hxx %target%
copy %src%\Handle_ShapeFix_Solid.hxx %target%
copy %src%\Handle_ShapeFix_Wire.hxx %target%
copy %src%\Handle_ShapeFix_Wireframe.hxx %target%
copy %src%\Handle_Standard_ConstructionError.hxx %target%
copy %src%\Handle_Standard_DomainError.hxx %target%
copy %src%\Handle_Standard_Failure.hxx %target%
copy %src%\Handle_Standard_NoSuchObject.hxx %target%
copy %src%\Handle_Standard_OutOfRange.hxx %target%
copy %src%\Handle_Standard_RangeError.hxx %target%
copy %src%\Handle_Standard_Transient.hxx %target%
copy %src%\Handle_Standard_Type.hxx %target%
copy %src%\Handle_Standard_TypeMismatch.hxx %target%
copy %src%\Handle_TColgp_HArray1OfPnt2d.hxx %target%
copy %src%\Handle_TColgp_HArray2OfPnt.hxx %target%
copy %src%\Handle_TColgp_SequenceNodeOfSequenceOfPnt.hxx %target%
copy %src%\Handle_TCollection_MapNode.hxx %target%
copy %src%\Handle_TCollection_SeqNode.hxx %target%
copy %src%\Handle_TColStd_HSequenceOfInteger.hxx %target%
copy %src%\Handle_TColStd_SequenceNodeOfSequenceOfReal.hxx %target%
copy %src%\Handle_TopLoc_Datum3D.hxx %target%
copy %src%\Handle_TopLoc_SListNodeOfSListOfItemLocation.hxx %target%
copy %src%\Handle_TopoDS_ListNodeOfListOfShape.hxx %target%
copy %src%\Handle_TopoDS_TCompound.hxx %target%
copy %src%\Handle_TopoDS_TCompSolid.hxx %target%
copy %src%\Handle_TopoDS_TFace.hxx %target%
copy %src%\Handle_TopoDS_TShape.hxx %target%
copy %src%\Handle_TopoDS_TShell.hxx %target%
copy %src%\Handle_TopoDS_TSolid.hxx %target%
copy %src%\Handle_TopoDS_TVertex.hxx %target%
copy %src%\Handle_TopoDS_TWire.hxx %target%
copy %src%\Handle_TopOpeBRepBuild_HBuilder.hxx %target%
copy %src%\Handle_TopTools_DataMapNodeOfDataMapOfIntegerListOfShape.hxx %target%
copy %src%\Handle_TopTools_DataMapNodeOfDataMapOfIntegerShape.hxx %target%
copy %src%\Handle_TopTools_DataMapNodeOfDataMapOfShapeInteger.hxx %target%
copy %src%\Handle_TopTools_DataMapNodeOfDataMapOfShapeListOfShape.hxx %target%
copy %src%\Handle_TopTools_DataMapNodeOfDataMapOfShapeReal.hxx %target%
copy %src%\Handle_TopTools_DataMapNodeOfDataMapOfShapeShape.hxx %target%
copy %src%\Handle_TopTools_HSequenceOfShape.hxx %target%
copy %src%\Handle_TopTools_IndexedDataMapNodeOfIndexedDataMapOfShapeListOfShape.hxx %target%
copy %src%\Handle_TopTools_IndexedDataMapNodeOfIndexedDataMapOfShapeShape.hxx %target%
copy %src%\Handle_TopTools_IndexedMapNodeOfIndexedMapOfShape.hxx %target%
copy %src%\Handle_TopTools_ListNodeOfListOfShape.hxx %target%
copy %src%\Handle_TopTools_SequenceNodeOfSequenceOfShape.hxx %target%
copy %src%\Handle_TopTools_StdMapNodeOfMapOfShape.hxx %target%
copy %src%\Handle_TShort_HArray1OfShortReal.hxx %target%
copy %src%\LProp_Status.hxx %target%
copy %src%\math_FunctionSet.hxx %target%
copy %src%\math_FunctionSetWithDerivatives.hxx %target%
copy %src%\Message_Gravity.hxx %target%
copy %src%\MMgt_TShared.hxx %target%
copy %src%\NCollection_BaseAllocator.hxx %target%
copy %src%\NCollection_BaseCollection.hxx %target%
copy %src%\NCollection_BaseList.hxx %target%
copy %src%\NCollection_DefineAlloc.hxx %target%
copy %src%\NCollection_Handle.hxx %target%
copy %src%\NCollection_IncAllocator.hxx %target%
copy %src%\NCollection_List.hxx %target%
copy %src%\NCollection_ListNode.hxx %target%
copy %src%\NCollection_TListIterator.hxx %target%
copy %src%\NCollection_TListNode.hxx %target%
copy %src%\NCollection_TypeDef.hxx %target%
copy %src%\NCollection_UBTree.hxx %target%
copy %src%\NCollection_UBTreeFiller.hxx %target%
copy %src%\NCollection_Vector.hxx %target%
copy %src%\Poly.hxx %target%
copy %src%\Poly_Array1OfTriangle.hxx %target%
copy %src%\Poly_ListOfTriangulation.hxx %target%
copy %src%\Poly_Triangle.hxx %target%
copy %src%\Poly_Triangle.lxx %target%
copy %src%\Poly_Triangulation.hxx %target%
copy %src%\Poly_Triangulation.lxx %target%
copy %src%\Precision.hxx %target%
copy %src%\Precision.lxx %target%
copy %src%\Quantity_Length.hxx %target%
copy %src%\Quantity_Parameter.hxx %target%
copy %src%\Quantity_PlaneAngle.hxx %target%
copy %src%\ShapeAnalysis_FreeBounds.hxx %target%
copy %src%\ShapeAnalysis_FreeBounds.lxx %target%
copy %src%\ShapeAnalysis_Wire.hxx %target%
copy %src%\ShapeAnalysis_Wire.lxx %target%
copy %src%\ShapeBuild_ReShape.hxx %target%
copy %src%\ShapeExtend.hxx %target%
copy %src%\ShapeExtend_Status.hxx %target%
copy %src%\ShapeExtend_WireData.hxx %target%
copy %src%\ShapeFix_Face.hxx %target%
copy %src%\ShapeFix_Face.lxx %target%
copy %src%\ShapeFix_IntersectionTool.hxx %target%
copy %src%\ShapeFix_IntersectionTool.lxx %target%
copy %src%\ShapeFix_Root.hxx %target%
copy %src%\ShapeFix_Root.lxx %target%
copy %src%\ShapeFix_Shape.hxx %target%
copy %src%\ShapeFix_Shape.lxx %target%
copy %src%\ShapeFix_ShapeTolerance.hxx %target%
copy %src%\ShapeFix_Shell.hxx %target%
copy %src%\ShapeFix_Shell.lxx %target%
copy %src%\ShapeFix_Solid.hxx %target%
copy %src%\ShapeFix_Solid.lxx %target%
copy %src%\ShapeFix_Wire.hxx %target%
copy %src%\ShapeFix_Wire.lxx %target%
copy %src%\ShapeFix_Wireframe.hxx %target%
copy %src%\ShapeFix_Wireframe.lxx %target%
copy %src%\ShapeUpgrade_ShellSewing.hxx %target%
copy %src%\Standard.hxx %target%
copy %src%\Standard_Address.hxx %target%
copy %src%\Standard_Boolean.hxx %target%
copy %src%\Standard_Character.hxx %target%
copy %src%\Standard_ConstructionError.hxx %target%
copy %src%\Standard_CString.hxx %target%
copy %src%\Standard_ctype.hxx %target%
copy %src%\Standard_DefineAlloc.hxx %target%
copy %src%\Standard_DefineException.hxx %target%
copy %src%\Standard_DefineHandle.hxx %target%
copy %src%\Standard_DomainError.hxx %target%
copy %src%\Standard_ExtCharacter.hxx %target%
copy %src%\Standard_ExtString.hxx %target%
copy %src%\Standard_Failure.hxx %target%
copy %src%\Standard_Failure.lxx %target%
copy %src%\Standard_Integer.hxx %target%
copy %src%\Standard_IStream.hxx %target%
copy %src%\Standard_KindOfType.hxx %target%
copy %src%\Standard_Macro.hxx %target%
copy %src%\Standard_math.hxx %target%
copy %src%\Standard_NoSuchObject.hxx %target%
copy %src%\Standard_OStream.hxx %target%
copy %src%\Standard_OutOfRange.hxx %target%
copy %src%\Standard_PrimitiveTypes.hxx %target%
copy %src%\Standard_RangeError.hxx %target%
copy %src%\Standard_Real.hxx %target%
copy %src%\Standard_ShortReal.hxx %target%
copy %src%\Standard_Size.hxx %target%
copy %src%\Standard_SStream.hxx %target%
copy %src%\Standard_Storable.hxx %target%
copy %src%\Standard_Stream.hxx %target%
copy %src%\Standard_Transient.hxx %target%
copy %src%\Standard_Transient_proto.hxx %target%
copy %src%\Standard_Type.hxx %target%
copy %src%\Standard_Type.lxx %target%
copy %src%\Standard_TypeDef.hxx %target%
copy %src%\Standard_TypeMismatch.hxx %target%
copy %src%\Standard_values.h %target%
copy %src%\Sweep_NumShape.hxx %target%
copy %src%\Sweep_NumShape.lxx %target%
copy %src%\Sweep_NumShapeTool.hxx %target%
copy %src%\TColgp_Array1OfPnt.hxx %target%
copy %src%\TColgp_SequenceOfPnt.hxx %target%
copy %src%\TCollection_Array1.lxx %target%
copy %src%\TCollection_Array2.lxx %target%
copy %src%\TCollection_BaseSequence.hxx %target%
copy %src%\TCollection_BaseSequence.lxx %target%
copy %src%\TCollection_BasicMap.hxx %target%
copy %src%\TCollection_BasicMap.lxx %target%
copy %src%\TCollection_HSequence.lxx %target%
copy %src%\TCollection_List.lxx %target%
copy %src%\TCollection_ListIterator.lxx %target%
copy %src%\TCollection_Sequence.lxx %target%
copy %src%\TCollection_SList.lxx %target%
copy %src%\TColStd_Array1OfReal.hxx %target%
copy %src%\TColStd_Array2OfBoolean.hxx %target%
copy %src%\TColStd_SequenceOfReal.hxx %target%
copy %src%\TopAbs.hxx %target%
copy %src%\TopAbs_Orientation.hxx %target%
copy %src%\TopAbs_ShapeEnum.hxx %target%
copy %src%\TopAbs_State.hxx %target%
copy %src%\TopExp_Explorer.hxx %target%
copy %src%\TopExp_Explorer.lxx %target%
copy %src%\TopExp_Stack.hxx %target%
copy %src%\TopLoc_ItemLocation.hxx %target%
copy %src%\TopLoc_Location.hxx %target%
copy %src%\TopLoc_Location.lxx %target%
copy %src%\TopLoc_SListOfItemLocation.hxx %target%
copy %src%\TopLoc_TrsfPtr.hxx %target%
copy %src%\TopoDS.hxx %target%
copy %src%\TopoDS.lxx %target%
copy %src%\TopoDS_Builder.hxx %target%
copy %src%\TopoDS_Builder.lxx %target%
copy %src%\TopoDS_Compound.hxx %target%
copy %src%\TopoDS_Compound.lxx %target%
copy %src%\TopoDS_CompSolid.hxx %target%
copy %src%\TopoDS_CompSolid.lxx %target%
copy %src%\TopoDS_Edge.hxx %target%
copy %src%\TopoDS_Edge.lxx %target%
copy %src%\TopoDS_Face.hxx %target%
copy %src%\TopoDS_Face.lxx %target%
copy %src%\TopoDS_Iterator.hxx %target%
copy %src%\TopoDS_Iterator.lxx %target%
copy %src%\TopoDS_ListIteratorOfListOfShape.hxx %target%
copy %src%\TopoDS_ListOfShape.hxx %target%
copy %src%\TopoDS_Shape.hxx %target%
copy %src%\TopoDS_Shape.lxx %target%
copy %src%\TopoDS_Shell.hxx %target%
copy %src%\TopoDS_Shell.lxx %target%
copy %src%\TopoDS_Solid.hxx %target%
copy %src%\TopoDS_Solid.lxx %target%
copy %src%\TopoDS_TCompound.hxx %target%
copy %src%\TopoDS_TCompound.lxx %target%
copy %src%\TopoDS_TCompSolid.hxx %target%
copy %src%\TopoDS_TCompSolid.lxx %target%
copy %src%\TopoDS_TFace.hxx %target%
copy %src%\TopoDS_TFace.lxx %target%
copy %src%\TopoDS_TShape.hxx %target%
copy %src%\TopoDS_TShape.lxx %target%
copy %src%\TopoDS_TShell.hxx %target%
copy %src%\TopoDS_TShell.lxx %target%
copy %src%\TopoDS_TSolid.hxx %target%
copy %src%\TopoDS_TSolid.lxx %target%
copy %src%\TopoDS_TVertex.hxx %target%
copy %src%\TopoDS_TVertex.lxx %target%
copy %src%\TopoDS_TWire.hxx %target%
copy %src%\TopoDS_TWire.lxx %target%
copy %src%\TopoDS_Vertex.hxx %target%
copy %src%\TopoDS_Vertex.lxx %target%
copy %src%\TopoDS_Wire.hxx %target%
copy %src%\TopoDS_Wire.lxx %target%
copy %src%\TopTools_Array1OfShape.hxx %target%
copy %src%\TopTools_DataMapOfIntegerListOfShape.hxx %target%
copy %src%\TopTools_DataMapOfIntegerShape.hxx %target%
copy %src%\TopTools_DataMapOfShapeInteger.hxx %target%
copy %src%\TopTools_DataMapOfShapeListOfShape.hxx %target%
copy %src%\TopTools_DataMapOfShapeReal.hxx %target%
copy %src%\TopTools_DataMapOfShapeShape.hxx %target%
copy %src%\TopTools_HSequenceOfShape.hxx %target%
copy %src%\TopTools_IndexedDataMapOfShapeListOfShape.hxx %target%
copy %src%\TopTools_IndexedDataMapOfShapeShape.hxx %target%
copy %src%\TopTools_IndexedMapOfShape.hxx %target%
copy %src%\TopTools_ListOfShape.hxx %target%
copy %src%\TopTools_MapOfShape.hxx %target%
copy %src%\TopTools_SequenceOfShape.hxx %target%
copy %src%\TShort_Array1OfShortReal.hxx %target%