//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xbim.Query.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xbim.Query.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] ClassifyModelToNRM {
            get {
                object obj = ResourceManager.GetObject("ClassifyModelToNRM", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code; Description; Parent
        ///NRM; New Rules of Measurement
        ///01; Substructure; NRM
        ///01.01; Foundations; 01
        ///01.02; Basement Excavation; 01
        ///01.03; Basement Retaining Walls; 01
        ///01.04; Ground Floor Construction; 01
        ///02; Superstructure; NRM
        ///02.01; Frame; 02
        ///02.01.01; Steel Frames; 02.01
        ///02.01.02; Space Frames/Decks; 02.01
        ///02.01.03; Concrete Casings to Steel Frames; 02.01
        ///02.01.04; Concrete Frames; 02.01
        ///02.01.05; Timber Frames; 02.01
        ///02.01.06; Specialist Frames; 02.01
        ///02.02; Upper Floors; 02
        ///02.03; Roof [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NRM {
            get {
                return ResourceManager.GetString("NRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Code&quot;,&quot;Description&quot;,&quot;Parent&quot;,&quot;Table&quot;,&quot;Version&quot;
        ///&quot;A&quot;,&quot;Form of information&quot;,&quot;uniclass&quot;,&quot;A&quot;,&quot;1.4&quot;
        ///&quot;A1&quot;,&quot;General reference works&quot;,&quot;A&quot;,&quot;A&quot;,&quot;1.4&quot;
        ///&quot;A11&quot;,&quot;Dictionaries, encyclopedias&quot;,&quot;A1&quot;,&quot;A&quot;,&quot;1.4&quot;
        ///&quot;A111&quot;,&quot;Dictionaries&quot;,&quot;A11&quot;,&quot;A&quot;,&quot;1.4&quot;
        ///&quot;A112&quot;,&quot;Encyclopedias&quot;,&quot;A11&quot;,&quot;A&quot;,&quot;1.4&quot;
        ///&quot;A12&quot;,&quot;Guides, directories&quot;,&quot;A1&quot;,&quot;A&quot;,&quot;1.4&quot;
        ///&quot;A121&quot;,&quot;Guides&quot;,&quot;A12&quot;,&quot;A&quot;,&quot;1.4&quot;
        ///&quot;A122&quot;,&quot;Directories&quot;,&quot;A12&quot;,&quot;A&quot;,&quot;1.4&quot;
        ///&quot;A13&quot;,&quot;Catalogues&quot;,&quot;A1&quot;,&quot;A&quot;,&quot;1.4&quot;
        ///&quot;A14&quot;,&quot;Surveys, maps&quot;,&quot;A1&quot;,&quot;A&quot;,&quot;1.4&quot;
        ///&quot;A15&quot;,&quot;Statistics&quot;,&quot;A1&quot;,&quot;A&quot;,&quot;1.4&quot;
        ///&quot;A16&quot;,&quot;Price bo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Uniclass {
            get {
                return ResourceManager.GetString("Uniclass", resourceCulture);
            }
        }
    }
}
